steps:
# Build the blockchain service container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/neurashield-blockchain:latest', '-f', 'backend/Dockerfile', 'backend']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/neurashield-blockchain:latest']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'neurashield-blockchain'
  - '--image=gcr.io/$PROJECT_ID/neurashield-blockchain:latest'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--cpu=${_CPU}'
  - '--memory=${_MEMORY}'
  - '--timeout=3600s'
  - '--concurrency=1'
  - '--min-instances=1'
  - '--max-instances=10'
  - '--port=3001'
  - '--service-account=${_SERVICE_ACCOUNT}'
  - '--no-allow-unauthenticated'
  - '--vpc-connector=${_VPC_CONNECTOR}'
  - '--vpc-egress=all'

images:
- 'gcr.io/$PROJECT_ID/neurashield-blockchain:latest'

substitutions:
  _REGION: 'us-west1'
  _CPU: '1'
  _MEMORY: '2Gi'
  _SERVICE_ACCOUNT: 'neurashield-blockchain@${PROJECT_ID}.iam.gserviceaccount.com'
  _VPC_CONNECTOR: 'neurashield-vpc-connector'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 