apiVersion: v1
kind: ResourceQuota
metadata:
  name: fabric-quota
  namespace: neurashield
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
    services.nodeports: "0" 