global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.org:587'
  smtp_from: 'alerts@neurashield.com'
  smtp_auth_username: 'alerts@neurashield.com'
  smtp_auth_password: 'password'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'ops-team'
  
  routes:
    - match:
        severity: critical
      receiver: 'ops-team'
      continue: true
    
    - match:
        service: ai-model
      receiver: 'ai-team'
      
    - match:
        service: backend
      receiver: 'backend-team'

receivers:
  - name: 'ops-team'
    email_configs:
      - to: 'ops-team@example.org'
        send_resolved: true
  
  - name: 'ai-team'
    email_configs:
      - to: 'ai-team@example.org'
        send_resolved: true
    
  - name: 'backend-team'
    email_configs:
      - to: 'backend-team@example.org'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job'] 