apiVersion: apps/v1
kind: Deployment
metadata:
  name: neurashield-backend
  namespace: neurashield
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neurashield-backend
  template:
    metadata:
      labels:
        app: neurashield-backend
    spec:
      containers:
      - name: backend
        image: neurashield-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        - containerPort: 3002
          name: metrics
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: METRICS_PORT
          value: "3002"
        - name: AI_SERVICE_URL
          value: "http://neurashield-ai:5000"
        - name: IPFS_URL
          value: "http://ipfs:5001"
        # GCP environment variables
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: gcp-config
              key: project_id
        - name: SERVICE_NAME
          value: "neurashield-backend"
        - name: SERVICE_VERSION
          valueFrom:
            configMapKeyRef:
              name: gcp-config
              key: service_version
        # Get service account credentials from secret
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/var/run/secrets/google/key.json"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
        - name: google-cloud-key
          mountPath: /var/run/secrets/google
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: backend-config
      - name: logs-volume
        emptyDir: {}
      - name: google-cloud-key
        secret:
          secretName: google-cloud-key
          optional: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - neurashield-backend
              topologyKey: kubernetes.io/hostname 