apiVersion: v1
kind: Service
metadata:
  name: fabric-ca
  labels:
    app: hyperledger
    component: ca
spec:
  ports:
    - port: 7054
      targetPort: 7054
      name: ca-port
    - port: 17054
      targetPort: 17054
      name: operations
  selector:
    app: hyperledger
    component: ca
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-orderer
  labels:
    app: hyperledger
    component: orderer
spec:
  ports:
    - port: 7050
      targetPort: 7050
      name: orderer-port
    - port: 17050
      targetPort: 17050
      name: operations
  selector:
    app: hyperledger
    component: orderer
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-peer
  labels:
    app: hyperledger
    component: peer
spec:
  ports:
    - port: 7051
      targetPort: 7051
      name: peer-port
    - port: 17051
      targetPort: 17051
      name: operations
  selector:
    app: hyperledger
    component: peer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      component: ca
  template:
    metadata:
      labels:
        app: hyperledger
        component: ca
    spec:
      volumes:
        - name: ca-data
          persistentVolumeClaim:
            claimName: fabric-ca-data
      containers:
        - name: ca
          image: hyperledger/fabric-ca:2.5.0
          ports:
            - containerPort: 7054
            - containerPort: 17054
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca.org1.example.com
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_PORT
              value: "7054"
            - name: FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:17054
          volumeMounts:
            - name: ca-data
              mountPath: /etc/hyperledger/fabric-ca-server
          command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      component: orderer
  template:
    metadata:
      labels:
        app: hyperledger
        component: orderer
    spec:
      volumes:
        - name: orderer-data
          persistentVolumeClaim:
            claimName: fabric-orderer-data
        - name: orderer-config
          configMap:
            name: fabric-orderer-config
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.5.0
          ports:
            - containerPort: 7050
            - containerPort: 17050
          env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /var/hyperledger/orderer/orderer.genesis.block
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /var/hyperledger/orderer/msp
            - name: ORDERER_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:17050
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
          volumeMounts:
            - name: orderer-data
              mountPath: /var/hyperledger/production/orderer
            - name: orderer-config
              mountPath: /var/hyperledger/orderer
          command: ["orderer"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      component: peer
  template:
    metadata:
      labels:
        app: hyperledger
        component: peer
    spec:
      volumes:
        - name: peer-data
          persistentVolumeClaim:
            claimName: fabric-peer-data
        - name: peer-config
          configMap:
            name: fabric-peer-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      containers:
        - name: peer
          image: hyperledger/fabric-peer:2.5.0
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 17051
          env:
            - name: CORE_VM_ENDPOINT
              value: unix:///host/var/run/docker.sock
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "false"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /etc/hyperledger/fabric/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /etc/hyperledger/fabric/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /etc/hyperledger/fabric/tls/ca.crt
            - name: CORE_PEER_ID
              value: peer0.org1.example.com
            - name: CORE_PEER_ADDRESS
              value: peer0.org1.example.com:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_CHAINCODEADDRESS
              value: peer0.org1.example.com:7052
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0.org1.example.com:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: peer0.org1.example.com:7051
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:17051
          volumeMounts:
            - name: docker-socket
              mountPath: /host/var/run/docker.sock
            - name: peer-config
              mountPath: /etc/hyperledger/fabric
            - name: peer-data
              mountPath: /var/hyperledger/production
          command: ["peer", "node", "start"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-ca-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-orderer-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-peer-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 