apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: neurashield-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: neurashield
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: neurashield-alerts
  namespace: monitoring
spec:
  groups:
  - name: neurashield
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: Error rate is above 10% for the last 5 minutes
    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: 95th percentile latency is above 1 second
    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{container="backend"} / container_spec_memory_limit_bytes{container="backend"} > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Memory usage is above 90% of limit
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{container="backend"}[5m]) / container_spec_cpu_quota{container="backend"} > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage
        description: CPU usage is above 90% of limit
    - alert: ModelAccuracyLow
      expr: model_accuracy < 0.8
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: Low model accuracy
        description: Model accuracy is below 80%
    - alert: BlockchainSyncIssue
      expr: blockchain_sync_status == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Blockchain sync issue
        description: Blockchain node is not syncing
---
apiVersion: monitoring.coreos.com/v1
kind: GrafanaDashboard
metadata:
  name: neurashield-dashboard
  namespace: monitoring
spec:
  json: |
    {
      "annotations": {
        "list": []
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 1,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "rate(http_requests_total[5m])",
              "interval": "",
              "legendFormat": "{{status}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Request Rate",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "schemaVersion": 22,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "NeuraShield Dashboard",
      "uid": "neurashield",
      "version": 1
    } 