apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neurashield-frontend-policy
spec:
  podSelector:
    matchLabels:
      app: neurashield
      component: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: neurashield
          component: backend
    ports:
    - protocol: TCP
      port: 3001
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neurashield-backend-policy
spec:
  podSelector:
    matchLabels:
      app: neurashield
      component: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield
          component: frontend
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3001
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: neurashield
          component: ai
    ports:
    - protocol: TCP
      port: 5000
  - to:
    - podSelector:
        matchLabels:
          app: neurashield
          component: ipfs
    ports:
    - protocol: TCP
      port: 5001
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neurashield-ai-policy
spec:
  podSelector:
    matchLabels:
      app: neurashield
      component: ai
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield
          component: backend
    - namespaceSelector:
        matchLabels:
          name: prometheus
    ports:
    - protocol: TCP
      port: 5000
    - protocol: TCP
      port: 8000
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: neurashield-ipfs-policy
spec:
  podSelector:
    matchLabels:
      app: neurashield
      component: ipfs
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield
          component: backend
    ports:
    - protocol: TCP
      port: 5001
  egress: [] 