apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
  namespace: neurashield
spec:
  podSelector:
    matchLabels:
      app: neurashield-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: neurashield-backend
    ports:
    - protocol: TCP
      port: 3001

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: neurashield
spec:
  podSelector:
    matchLabels:
      app: neurashield-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield-frontend
    ports:
    - protocol: TCP
      port: 3001
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: neurashield-blockchain
    ports:
    - protocol: TCP
      port: 8080
  - to:
    - podSelector:
        matchLabels:
          app: neurashield-ai
    ports:
    - protocol: TCP
      port: 5000
  - to:
    - podSelector:
        matchLabels:
          app: neurashield-ipfs
    ports:
    - protocol: TCP
      port: 5001
  - to:
    - namespaceSelector: {}
      podSelector: {}
    ports:
    - protocol: UDP
      port: 53
  
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blockchain-policy
  namespace: neurashield
spec:
  podSelector:
    matchLabels:
      app: neurashield-blockchain
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield-backend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector: {}
      podSelector: {}
    ports:
    - protocol: UDP
      port: 53
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 7051  # For external blockchain network
    - protocol: TCP
      port: 7054  # For certificate authority
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-policy
  namespace: neurashield
spec:
  podSelector:
    matchLabels:
      app: neurashield-ai
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield-backend
    - namespaceSelector:
        matchLabels:
          name: prometheus
    ports:
    - protocol: TCP
      port: 5000
    - protocol: TCP
      port: 8000
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipfs-policy
  namespace: neurashield
spec:
  podSelector:
    matchLabels:
      app: neurashield-ipfs
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: neurashield-backend
    ports:
    - protocol: TCP
      port: 5001
    - protocol: TCP
      port: 8080
  egress: [] 