apiVersion: v1
kind: Secret
metadata:
  name: neurashield-secrets
type: Opaque
# For production, use something like:
# kubectl create secret generic neurashield-secrets \
#   --from-file=certs/fabric-ca.crt \
#   --from-file=certs/fabric-ca.key \
#   --from-literal=AI_API_KEY=actual-secret-ai-key \
#   --from-literal=JWT_SECRET=$(openssl rand -hex 32) \
#   --from-literal=IPFS_API_KEY=actual-ipfs-api-key
stringData:
  # These are placeholder values - replace with actual secrets in production
  FABRIC_CA_CERT: |
    -----BEGIN CERTIFICATE-----
    PLACEHOLDER_CERTIFICATE
    -----END CERTIFICATE-----
  FABRIC_CA_KEY: |
    -----BEGIN PRIVATE KEY-----
    PLACEHOLDER_PRIVATE_KEY
    -----END PRIVATE KEY-----
  AI_API_KEY: "your-ai-api-key"
  JWT_SECRET: "your-jwt-secret"
  IPFS_API_KEY: "your-ipfs-api-key" 