apiVersion: v1
kind: Secret
metadata:
  name: neurashield-secrets
type: Opaque
stringData:
  # These are placeholder values - replace with actual secrets in production
  FABRIC_CA_CERT: |
    -----BEGIN CERTIFICATE-----
    PLACEHOLDER_CERTIFICATE
    -----END CERTIFICATE-----
  FABRIC_CA_KEY: |
    -----BEGIN PRIVATE KEY-----
    PLACEHOLDER_PRIVATE_KEY
    -----END PRIVATE KEY-----
  AI_API_KEY: "your-ai-api-key"
  JWT_SECRET: "your-jwt-secret"
  IPFS_API_KEY: "your-ipfs-api-key" 