apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
  resources:
  - group: ""
    resources: ["pods", "services", "configmaps", "secrets"]
  - group: "apps"
    resources: ["deployments", "statefulsets"]
- level: Request
  resources:
  - group: ""
    resources: ["pods/exec", "pods/portforward"]
- level: RequestResponse
  resources:
  - group: ""
    resources: ["secrets"]
- level: None
  resources:
  - group: ""
    resources: ["endpoints", "services/status"]
  omitStages:
  - "RequestReceived" 